[settings]
disable_backends = ["ubi", "asdf"]
lockfile = true

[tools]
rust = "1.95.0"
"aqua:gittower/git-flow-next" = "1.1.0"
"aqua:rhysd/actionlint" = "1.7.12"
"aqua:nektos/act" = "0.2.89"
"aqua:orhun/git-cliff" = "2.13.1"
